### ISSUE TITLE
AttributeError: 'module' object has no attribute 'HISTCMP_CORREL'

### ISSUE THREAD

**Issue by AlexunderMicrocontrol** [eduardofv/whale_detector#1]
Hi edouardo. at first thanks for sharing your code. 
After having a lot of trouble with installing opencv on mac I wanted to run your code but it fails in line 44 with 
-- AttributeError: 'module' object has no attribute 'HISTCMP_CORREL'
i also tryed to change this line into
sim = [cv2.compareHist(histg, getHist(imx), cv2.cv.CV_COMP_CORREL) for imx in images]
but than i run into this error

cv2.error: /tmp/opencv20150611-92017-pixpdt/opencv-2.4.11/modules/imgproc/src/histogram.cpp:1985: error: (-215) H1.type() == H2.type() && H1.type() == CV_32F

could you help me please

**Comment by eduardofv** [comment]
Hi Alex, certainly I'm not an expert on OpenCV but from the error it seem you have installed OpenCV 2.4. I've been using OpenCV 3.0 and there are some changes in those constants. Maybe cv2.CV_COMP_CORREL may work. Check docs on http://docs.opencv.org/2.4/modules/imgproc/doc/histograms.html or look for the specific example of OpenCV 2.4 histogram comparison in python. Hope this helps.
